//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34209
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whizz_Hard_Books_201313819.servicioweb {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.Whizz_Hard_Books.com/", ConfigurationName="servicioweb.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/conectarServidor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool conectarServidor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/conectarServidor", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> conectarServidorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Registrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Registrar(string tabla, string campos, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Registrar", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> RegistrarAsync(string tabla, string campos, string valor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/cantidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int cantidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/cantidad", ReplyAction="*")]
        System.Threading.Tasks.Task<int> cantidadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/existencias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int existencias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/existencias", ReplyAction="*")]
        System.Threading.Tasks.Task<int> existenciasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda_nombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet busqueda_nombre(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda_nombre", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> busqueda_nombreAsync(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/reservados_consulta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet reservados_consulta(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/reservados_consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> reservados_consultaAsync(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda_autor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet busqueda_autor(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda_autor", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> busqueda_autorAsync(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet busqueda(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> busquedaAsync(string IDMask);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/carnet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int carnet();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/carnet", ReplyAction="*")]
        System.Threading.Tasks.Task<int> carnetAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/reserva_no", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int reserva_no();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/reserva_no", ReplyAction="*")]
        System.Threading.Tasks.Task<int> reserva_noAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/disponibles", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int disponibles(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/disponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<int> disponiblesAsync(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/top", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int top(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/top", ReplyAction="*")]
        System.Threading.Tasks.Task<int> topAsync(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/prestamos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int prestamos(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/prestamos", ReplyAction="*")]
        System.Threading.Tasks.Task<int> prestamosAsync(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Reservados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int Reservados(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Reservados", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ReservadosAsync(string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/nprestados_cliente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int nprestados_cliente(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/nprestados_cliente", ReplyAction="*")]
        System.Threading.Tasks.Task<int> nprestados_clienteAsync(string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/fechahoy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string fechahoy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/fechahoy", ReplyAction="*")]
        System.Threading.Tasks.Task<string> fechahoyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_Prestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_Prestamo(string tabla, int prestamo, string libro, int disponibles, int top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_Prestamo", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Update_PrestamoAsync(string tabla, int prestamo, string libro, int disponibles, int top);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_Reserva", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_Reserva(string tabla, int reservas, string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_Reserva", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Update_ReservaAsync(string tabla, int reservas, string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_clientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_clientes(string tabla, int prestamos, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_clientes", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Update_clientesAsync(string tabla, int prestamos, string cliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/nprestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int nprestamo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/nprestamo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> nprestamoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/select_prestamo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int select_prestamo(string carnet, string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/select_prestamo", ReplyAction="*")]
        System.Threading.Tasks.Task<int> select_prestamoAsync(string carnet, string libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_devolucion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool Update_devolucion(int prestamo, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/Update_devolucion", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> Update_devolucionAsync(int prestamo, string fecha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda_masvendidos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet busqueda_masvendidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.Whizz_Hard_Books.com/busqueda_masvendidos", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> busqueda_masvendidosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : Whizz_Hard_Books_201313819.servicioweb.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Whizz_Hard_Books_201313819.servicioweb.ServiceSoap>, Whizz_Hard_Books_201313819.servicioweb.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool conectarServidor() {
            return base.Channel.conectarServidor();
        }
        
        public System.Threading.Tasks.Task<bool> conectarServidorAsync() {
            return base.Channel.conectarServidorAsync();
        }
        
        public bool Registrar(string tabla, string campos, string valor) {
            return base.Channel.Registrar(tabla, campos, valor);
        }
        
        public System.Threading.Tasks.Task<bool> RegistrarAsync(string tabla, string campos, string valor) {
            return base.Channel.RegistrarAsync(tabla, campos, valor);
        }
        
        public int cantidad() {
            return base.Channel.cantidad();
        }
        
        public System.Threading.Tasks.Task<int> cantidadAsync() {
            return base.Channel.cantidadAsync();
        }
        
        public int existencias() {
            return base.Channel.existencias();
        }
        
        public System.Threading.Tasks.Task<int> existenciasAsync() {
            return base.Channel.existenciasAsync();
        }
        
        public System.Data.DataSet busqueda_nombre(string IDMask) {
            return base.Channel.busqueda_nombre(IDMask);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> busqueda_nombreAsync(string IDMask) {
            return base.Channel.busqueda_nombreAsync(IDMask);
        }
        
        public System.Data.DataSet reservados_consulta(string IDMask) {
            return base.Channel.reservados_consulta(IDMask);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> reservados_consultaAsync(string IDMask) {
            return base.Channel.reservados_consultaAsync(IDMask);
        }
        
        public System.Data.DataSet busqueda_autor(string IDMask) {
            return base.Channel.busqueda_autor(IDMask);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> busqueda_autorAsync(string IDMask) {
            return base.Channel.busqueda_autorAsync(IDMask);
        }
        
        public System.Data.DataSet busqueda(string IDMask) {
            return base.Channel.busqueda(IDMask);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> busquedaAsync(string IDMask) {
            return base.Channel.busquedaAsync(IDMask);
        }
        
        public int carnet() {
            return base.Channel.carnet();
        }
        
        public System.Threading.Tasks.Task<int> carnetAsync() {
            return base.Channel.carnetAsync();
        }
        
        public int reserva_no() {
            return base.Channel.reserva_no();
        }
        
        public System.Threading.Tasks.Task<int> reserva_noAsync() {
            return base.Channel.reserva_noAsync();
        }
        
        public int disponibles(string libro) {
            return base.Channel.disponibles(libro);
        }
        
        public System.Threading.Tasks.Task<int> disponiblesAsync(string libro) {
            return base.Channel.disponiblesAsync(libro);
        }
        
        public int top(string libro) {
            return base.Channel.top(libro);
        }
        
        public System.Threading.Tasks.Task<int> topAsync(string libro) {
            return base.Channel.topAsync(libro);
        }
        
        public int prestamos(string libro) {
            return base.Channel.prestamos(libro);
        }
        
        public System.Threading.Tasks.Task<int> prestamosAsync(string libro) {
            return base.Channel.prestamosAsync(libro);
        }
        
        public int Reservados(string libro) {
            return base.Channel.Reservados(libro);
        }
        
        public System.Threading.Tasks.Task<int> ReservadosAsync(string libro) {
            return base.Channel.ReservadosAsync(libro);
        }
        
        public int nprestados_cliente(string cliente) {
            return base.Channel.nprestados_cliente(cliente);
        }
        
        public System.Threading.Tasks.Task<int> nprestados_clienteAsync(string cliente) {
            return base.Channel.nprestados_clienteAsync(cliente);
        }
        
        public string fechahoy() {
            return base.Channel.fechahoy();
        }
        
        public System.Threading.Tasks.Task<string> fechahoyAsync() {
            return base.Channel.fechahoyAsync();
        }
        
        public bool Update_Prestamo(string tabla, int prestamo, string libro, int disponibles, int top) {
            return base.Channel.Update_Prestamo(tabla, prestamo, libro, disponibles, top);
        }
        
        public System.Threading.Tasks.Task<bool> Update_PrestamoAsync(string tabla, int prestamo, string libro, int disponibles, int top) {
            return base.Channel.Update_PrestamoAsync(tabla, prestamo, libro, disponibles, top);
        }
        
        public bool Update_Reserva(string tabla, int reservas, string libro) {
            return base.Channel.Update_Reserva(tabla, reservas, libro);
        }
        
        public System.Threading.Tasks.Task<bool> Update_ReservaAsync(string tabla, int reservas, string libro) {
            return base.Channel.Update_ReservaAsync(tabla, reservas, libro);
        }
        
        public bool Update_clientes(string tabla, int prestamos, string cliente) {
            return base.Channel.Update_clientes(tabla, prestamos, cliente);
        }
        
        public System.Threading.Tasks.Task<bool> Update_clientesAsync(string tabla, int prestamos, string cliente) {
            return base.Channel.Update_clientesAsync(tabla, prestamos, cliente);
        }
        
        public int nprestamo() {
            return base.Channel.nprestamo();
        }
        
        public System.Threading.Tasks.Task<int> nprestamoAsync() {
            return base.Channel.nprestamoAsync();
        }
        
        public int select_prestamo(string carnet, string libro) {
            return base.Channel.select_prestamo(carnet, libro);
        }
        
        public System.Threading.Tasks.Task<int> select_prestamoAsync(string carnet, string libro) {
            return base.Channel.select_prestamoAsync(carnet, libro);
        }
        
        public bool Update_devolucion(int prestamo, string fecha) {
            return base.Channel.Update_devolucion(prestamo, fecha);
        }
        
        public System.Threading.Tasks.Task<bool> Update_devolucionAsync(int prestamo, string fecha) {
            return base.Channel.Update_devolucionAsync(prestamo, fecha);
        }
        
        public System.Data.DataSet busqueda_masvendidos() {
            return base.Channel.busqueda_masvendidos();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> busqueda_masvendidosAsync() {
            return base.Channel.busqueda_masvendidosAsync();
        }
    }
}
